#-----------------------------------------------------------------------------------------------------------------------
# GENERAL
#-----------------------------------------------------------------------------------------------------------------------

# Define the stages of the pipeline.
stages:
    - check
    - pages
    - build
    - test


#-----------------------------------------------------------------------------------------------------------------------
# CHECK
#-----------------------------------------------------------------------------------------------------------------------

check:syntax:
    stage: check
    script:
        - exit 0
    allow_failure: true


#-----------------------------------------------------------------------------------------------------------------------
# PAGES
#-----------------------------------------------------------------------------------------------------------------------

pages:doxygen:
    stage: pages
    tags:
        - nginx
    script:
        - doxygen Doxyfile
        - rm -r /usr/share/nginx/html
        - mv doxy/html /usr/share/nginx
    only:
        - master


#-----------------------------------------------------------------------------------------------------------------------
# BUILD
#-----------------------------------------------------------------------------------------------------------------------

build:linux-amd64:
    stage: build
    tags:
        - linux
        - amd64
    script:
        - mkdir -p build/debug
        - cd build/debug
        - CC=clang CXX=clang++ cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ../..
        - ninja
    artifacts:
        paths:
            - build/debug/bin/
        expire_in: 1 day
    #only:
        #refs:
            #- ci
            #- merge_requests


#-----------------------------------------------------------------------------------------------------------------------
# TEST
#-----------------------------------------------------------------------------------------------------------------------

unittest:linux-amd64:
    stage: test
    tags:
        - linux
        - amd64
    needs: ["build:linux-amd64"]
    script: build/debug/bin/unittest \[core\]

integrationtest:linux-amd64:
    stage: test
    tags:
        - linux
        - amd64
    needs: ["build:linux-amd64"]
    script:
        - python3 test/IntegrationTest.py -v
